### ISSUE TITLE
Add user to dialout group

### ISSUE THREAD

**Issue by yeyeto2788** [yeyeto2788/workstation-setup-ansible#1]
For using 3D printers, development boards, etc it is helpful to execute `sudo usermod -a -G dialout $USER` so all usb-tty devices can be used without needing to execute commands as `sudo`.

Consider checking if the user already belong to `dialout` group by `groups $USER`.

Maybe using built-in module would be something like this:

```yaml
user:
  name: testuser
  shell: /bin/bash
  groups:
    - testgroup1
    - testgroup2
    - testgroup3
  append: yes
```
